version: '3.8'

services:
  guardrails:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY   #requires OPENAI_API_KEY to be defined in .env file.
      - OPENAI_BASE_URL  #requires OPENAI_BASE_URL to be defined in .env file.
